classdef App < matlab.apps.AppBase

    % Properties that correspond to app components
    properties (Access = public)
        DiseaseDetectionUIFigure  matlab.ui.Figure
        BackgroundPanel           matlab.ui.container.Panel
        BackgroundAxes            matlab.ui.control.UIAxes
        TextArea                  matlab.ui.control.TextArea
        InsertPictureButton       matlab.ui.control.Button
        LanguageSwitch            matlab.ui.control.Switch
        InsertedImage             matlab.ui.control.Image
        PredictedPlantLabel       matlab.ui.control.Label
        TipLabel                  matlab.ui.control.Label
        DiseaseDetailsButton      matlab.ui.control.Button
        TreatmentOptionsButton    matlab.ui.control.Button
        ContactButton             matlab.ui.control.Button
        DiseaseNameMapping        containers.Map
        CurrentDiseaseEnglish     string
    end

    % Component initialization
    % Component initialization
    methods (Access = private)

    % Create UIFigure and components
    function createComponents(app)

        % Create DiseaseDetectionUIFigure
        app.DiseaseDetectionUIFigure = uifigure('Name', 'Disease Detection');
        app.DiseaseDetectionUIFigure.Position = [100 100 800 600]; % Set the figure position

        % Create BackgroundPanel
        app.BackgroundPanel = uipanel(app.DiseaseDetectionUIFigure);
        app.BackgroundPanel.BackgroundColor = [255/255, 228/255, 181/255];
        app.BackgroundPanel.Position = [1,1,834,604]; % Adjust the panel size

        % Create BackgroundAxes
        app.BackgroundAxes = uiaxes(app.BackgroundPanel);
        app.BackgroundAxes.Position = [1,1,834,604]; % Adjust the axes size
        imshow("D:\Downloads\imaginefundal.jpg", 'Parent', app.BackgroundAxes); % Set background image here
        app.BackgroundAxes.XTick = [];
        app.BackgroundAxes.YTick = [];
        app.BackgroundAxes.Box = 'off';

        % Create TextArea
        app.TextArea = uitextarea(app.DiseaseDetectionUIFigure);
        app.TextArea.Position = [320 510 160 35]; % Adjust position of TextArea
        app.TextArea.Value = {'  Choose the picture required for the inspection'};
        app.TextArea.Editable = false; % Make the text non-editable

        % Create InsertPictureButton
        app.InsertPictureButton = uibutton(app.DiseaseDetectionUIFigure, 'push');
        app.InsertPictureButton.Position = [320 470 160 35]; % Adjust position of InsertPictureButton
        app.InsertPictureButton.Text = 'Insert Picture';
        app.InsertPictureButton.ButtonPushedFcn = @(src, event) insertPictureButtonPushed(app);

        % Create LanguageSwitch
        app.LanguageSwitch = uiswitch(app.DiseaseDetectionUIFigure, 'slider');
        app.LanguageSwitch.Items = {'ENG', 'RO'};
        app.LanguageSwitch.Position = [50, 510, 50, 22]; % Adjust position of the switch button
        app.LanguageSwitch.ValueChangedFcn = @(src, event) switchLanguage(app, src, event);

        % Create PredictedPlantLabel
        app.PredictedPlantLabel = uilabel(app.DiseaseDetectionUIFigure);
        app.PredictedPlantLabel.Position = [320 440 400 22]; % Adjust position of PredictedPlantLabel
        app.PredictedPlantLabel.Text = '';

        % Create TipLabel
        app.TipLabel = uilabel(app.DiseaseDetectionUIFigure);
        app.TipLabel.Text = '';

        % Create DiseaseDetailsButton
        app.DiseaseDetailsButton = uibutton(app.DiseaseDetectionUIFigure, 'push');
        app.DiseaseDetailsButton.Position = [320, 200, 160, 35]; % Adjust position of DiseaseDetailsButton
        app.DiseaseDetailsButton.Text = 'Disease Details';
        app.DiseaseDetailsButton.ButtonPushedFcn = @(src, event) DiseaseDetails(app);
        app.DiseaseDetailsButton.Visible = 'off'; % Set the button to be visible

        % Create TreatmentOptions Button
        app.TreatmentOptionsButton = uibutton(app.DiseaseDetectionUIFigure, 'push');
        app.TreatmentOptionsButton.Position = [320, 150, 160, 35];
        app.TreatmentOptionsButton.Text = 'Treatment Options';
        app.TreatmentOptionsButton.ButtonPushedFcn = @(src, event) TreatmentOptions(app);
        app.TreatmentOptionsButton.Visible = 'off'; % Set the button to be visible
        
        % Create Contact Button
        app.ContactButton = uibutton(app.DiseaseDetectionUIFigure, 'push');
        app.ContactButton.Position = [320, 100, 160, 35];
        app.ContactButton.Text = 'Contact Information';
        app.ContactButton.ButtonPushedFcn = @(src, event) ContactInfo(app);
        app.ContactButton.Visible = 'off';

        % Show the figure after all components are created
        app.DiseaseDetectionUIFigure.Visible = 'on';
    end


        % Function to add a border to an image
        function imgWithBorderPath = addImageBorder(~, imgPath, borderColor, borderWidth)
            img = imread(imgPath);
            % Create a border around the image
            border = uint8(ones(size(img, 1) + 2 * borderWidth, size(img, 2) + 2 * borderWidth, size(img, 3)) * 255);
            for c = 1:3
                border(:,:,c) = borderColor(c);
            end
            border(borderWidth+1:end-borderWidth, borderWidth+1:end-borderWidth, :) = img;
            % Convert the image with border to a format that can be used in the app
            imgWithBorderPath = [tempname, '.png'];
            imwrite(border, imgWithBorderPath);
        end


        function updateDiseaseLabelLanguage(app, language)
            % Check if the PredictedPlantLabel object exists and is valid
            if isempty(app.PredictedPlantLabel) || ~isvalid(app.PredictedPlantLabel)
                % If the label does not exist or is not valid, exit the function
                return;
            end
    
            % Now check if CurrentDiseaseEnglish has a valid value
            if isempty(app.CurrentDiseaseEnglish) || (~ischar(app.CurrentDiseaseEnglish) && ~isstring(app.CurrentDiseaseEnglish))
                % If there's no disease detected yet or the format is incorrect, exit the function
                return;
            end

            % Update the label based on the current language setting
            if language == "ENG"
                formattedLabel = strrep(app.CurrentDiseaseEnglish, '_', ' ');
                app.PredictedPlantLabel.Text = formattedLabel;
            elseif language == "RO"
                if isKey(app.DiseaseNameMapping, char(app.CurrentDiseaseEnglish))
                    app.PredictedPlantLabel.Text = app.DiseaseNameMapping(char(app.CurrentDiseaseEnglish));
                else
                    app.PredictedPlantLabel.Text = 'Boală necunoscută.'; % Placeholder text for unknown disease
                end
            end
        end


        function updateToolTipLanguage(app, language)
    % Check if the TipLabel object exists and is valid
            if isempty(app.TipLabel) || ~isvalid(app.TipLabel)
        % If the label does not exist or is not valid, exit the functiontable
                return;
            end
    % Only update the Tool Tip message if there is a valid disease detected
            if ~isempty(app.CurrentDiseaseEnglish)
                if language == "ENG"
                    app.TipLabel.Text = 'Tip: For better accuracy, cut off the leaf of the diseased plant and put it on a surface, in normal conditions of visibility. Then, take a picture.';
                elseif language == "RO"
                     app.TipLabel.Text = 'Sfat: Pentru o acuratețe mai bună, tăiați frunza plantei bolnave și pune-ți-o pe o suprafa, în condiții normale de vizibilitate. Apoi, faceți-i poză.';
                end
            end
        end


         function insertPictureButtonPushed(app)
            % Open file explorer to select an image
            [fileName, pathName] = uigetfile({'*.jpg;*.jpeg;*.png'}, 'Select an image');
            if ~isequal(fileName, 0)
                % Clear the previous background image
                cla(app.BackgroundAxes); % Clear the current axes
                app.BackgroundAxes.Visible = 'on';
                app.BackgroundAxes.Color = [255/255, 228/255, 181/255];
                app.BackgroundAxes.Box = 'off';
                app.BackgroundAxes.XColor = 'none';
                app.BackgroundAxes.YColor = 'none'; 
                app.BackgroundAxes.XTick = [];
                app.BackgroundAxes.YTick = [];
        
                % Load pre-trained GoogLeNet
                net1 = googlenet;
                targetSize = net1.Layers(1).InputSize;
        
                imagePath = fullfile(pathName, fileName);
                inputImage = imread(imagePath);
                resizedImage = imresize(inputImage, targetSize(1:2));
        
                % Load your models
                load('plant_disease_model.mat', 'convnet');
        
                % Classify the image with the models
                [predictedLabel1, scores1] = classify(convnet, resizedImage);
               
                % Set confidence threshold for plant disease classification
                confidenceThreshold = 0.79; % Adjust as needed
        
                % Check if the highest confidence score from either model is above the threshold
                if max(scores1) >= confidenceThreshold 
                    disp(['Predicted label using Model 1: ' char(predictedLabel1)]);
                else
                    disp('The provided image is not recognized as a plant disease.');
                end
        
                disp('Max score for Model 1:');
                disp(max(scores1));
                
        
                % Add a green border to the image and get the new image path
                imgWithBorderPath = app.addImageBorder(imagePath, [0, 155, 0], 10); % Green border with a width of 10 pixels
        
                % Display the image with border
                app.InsertedImage = uiimage(app.DiseaseDetectionUIFigure);
                app.InsertedImage.ImageSource = imgWithBorderPath;
                imgWidth = size(resizedImage, 2);
                imgHeight = size(resizedImage, 1);
                app.InsertedImage.Position = [(app.DiseaseDetectionUIFigure.Position(3) - imgWidth) / 2, (app.DiseaseDetectionUIFigure.Position(4) - imgHeight) / 2 + 170, imgWidth, imgHeight]; % Adjust position and size of the inserted image to account for the border
        
                % Update the text with the predicted plant label and the
                % tool tip
                app.PredictedPlantLabel = uilabel(app.DiseaseDetectionUIFigure);
                app.PredictedPlantLabel.Position = [app.InsertedImage.Position(1) + 30, app.InsertedImage.Position(2) - 30, 400, 22]; % Adjust position of the label
                if max(scores1) >= confidenceThreshold 
                    app.CurrentDiseaseEnglish = char(predictedLabel1);
                    updateDiseaseLabelLanguage(app, app.LanguageSwitch.Value);

                    app.TipLabel = uilabel(app.DiseaseDetectionUIFigure);
                    app.TipLabel.Position = [30, app.InsertedImage.Position(2) - 100, 800, 50];
                    updateToolTipLanguage(app, app.LanguageSwitch.Value);
                else
                    app.CurrentDiseaseEnglish = 'No disease detected.';
                    updateDiseaseLabelLanguage(app, app.LanguageSwitch.Value);
                    app.TipLabel.Text = '';

                end

                % Make the Disease Details Button visible after picture is classified
                app.DiseaseDetailsButton.Visible = 'on';
                app.TreatmentOptionsButton.Visible = 'on';
                app.ContactButton.Visible = 'on';
        
                % Hide unnecessary components
                app.TextArea.Visible = 'off';
                app.InsertPictureButton.Visible = 'off';
            end
        end
        
        
        function switchLanguage(app, src, ~)
            % Get the current value of the switch button
            selectedLanguage = src.Value;

            % Update the text of the components based on the selected language
            if strcmp(selectedLanguage, 'ENG')
                app.TextArea.Value = {'  Choose the picture required for the inspection'};
                app.InsertPictureButton.Text = 'Insert Picture';
                app.DiseaseDetailsButton.Text = 'Disease Details';
                app.TreatmentOptionsButton.Text = 'Treatment Options';
                app.ContactButton.Text = 'Contact Information';
                app.updateDiseaseLabelLanguage('ENG');

                if isempty(app.CurrentDiseaseEnglish) || strcmp(app.CurrentDiseaseEnglish, 'No disease detected.')
                % If no disease is detected or the message is 'No disease detected.', clear the tooltip
                    app.TipLabel.Text = '';
                else
                % Update and display the tooltip
                    app.updateToolTipLanguage('ENG');
                end

            elseif strcmp(selectedLanguage, 'RO')
                app.TextArea.Value = {'  Alegeți imaginea necesară pentru inspecție'};
                app.InsertPictureButton.Text = 'Inserați imaginea';
                app.DiseaseDetailsButton.Text = 'Detalii Boală';
                app.TreatmentOptionsButton.Text = 'Opțiuni de Tratament';
                app.ContactButton.Text = 'Informații de Contact';
                app.updateDiseaseLabelLanguage('RO');

                if isempty(app.CurrentDiseaseEnglish) || strcmp(app.CurrentDiseaseEnglish, 'No disease detected.')
                    % If no disease is detected or the message is 'No disease detected.', clear the tooltip
                    app.TipLabel.Text = '';
                else
                    % Update and display the tooltip
                    app.updateToolTipLanguage('RO');
                end

            end

            % Update the LanguageSwitch component text
            app.LanguageSwitch.Items = {'ENG', 'RO'}; % Update language options
        end
    
    
        function ContactInfo(app)
            contactInfo = struct(...
                'English', ["To contact the local authority or a relevant institution, please access the following: ", ...
                "   ", ...
                "➡️Website: https://www.anfdf.ro/", ...
                "➡️Email: fitosanitar@anfdf.ro / lccf@lccf.ro", ...
                "➡️Phone:  0212703254 / 0212703256"], ...
                'Romanian', ["Pentru a contacta autoritatea locală sau o instituție relevantă, vă rugam accesați următoarele: ", ...
                "   ", ...
                "➡️Website: https://www.anfdf.ro/", ...
                "➡️Email: fitosanitar@anfdf.ro / lccf@lccf.ro", ...
                "➡️Telefon: 0212703254 / 0212703256"]...
            );

            selectedLanguage = app.LanguageSwitch.Value;

            if strcmp(selectedLanguage, 'ENG')
                message = strrep(contactInfo.English, '\n\t', newline + "   ");
            elseif strcmp(selectedLanguage, 'RO')
                message = strrep(contactInfo.Romanian, '\n\t', newline + "   ");
            end
            
            if strcmp(selectedLanguage, 'ENG')
                uialert(app.DiseaseDetectionUIFigure, message, 'Contact Information', 'Icon', 'info');
            elseif strcmp(selectedLanguage, 'RO')
                uialert(app.DiseaseDetectionUIFigure, message, 'Informații de Contact', 'Icon', 'info');
            end

        end

        function DiseaseDetails(app)
            % Check if there is a currently detected disease
            if ~isempty(app.CurrentDiseaseEnglish)
                % Get the details for the current disease
                disease = app.CurrentDiseaseEnglish; % Assuming this is the disease name
                details = app.getDiseaseDetails(disease);

                % Check the selected language
                selectedLanguage = app.LanguageSwitch.Value;

                % Display the details in a message box based on the selected language
                if strcmp(selectedLanguage, 'ENG')
                    message = strrep(details.English, '\n\t', newline + "    ");
                elseif strcmp(selectedLanguage, 'RO')
                    message = strrep(details.Romanian, '\n\t', newline + "    ");
                else
                    message = 'Language not supported.';
                end

                if (message == "Details not available.") || (message == "Detalii indisponibile.")

             % If no disease is detected, show a message
                    if strcmp(selectedLanguage, 'ENG')
                        uialert(app.DiseaseDetectionUIFigure, message, 'No disease detected', 'Icon', 'error');
                    elseif strcmp(selectedLanguage, 'RO')
                        uialert(app.DiseaseDetectionUIFigure, message, 'Nicio boală detectată.', 'Icon', 'error');
                    end
                else

              % Display the details in a message box
                   if strcmp(selectedLanguage, 'ENG')
                        uialert(app.DiseaseDetectionUIFigure, message, 'Disease Details', 'Icon', 'success');
                   elseif strcmp(selectedLanguage, 'RO')
                        uialert(app.DiseaseDetectionUIFigure, message, 'Detalii Boală', 'Icon', 'success');
                   end
               end
            end
        end

        function details = getDiseaseDetails(app, disease)
            % Define disease details based on the disease name
            keys = {'Pepper__bell___Bacterial_spot',...
                    'Pepper__bell___healthy',...
                    'Potato___Early_blight',...
                    'Potato___healthy',...
                    'Potato___Late_blight',...
                    'Tomato_Early_blight',...
                    'Tomato_Late_blight',...
                    'Tomato_Leaf_Mold',...
                    'Tomato_Septoria_leaf_spot',...
                    'Tomato_Spider_mites_Two_spotted_spider_mite',...
                    'Tomato__Target_Spot',...
                    'Tomato__Tomato_mosaic_virus',...
                    'Tomato__Tomato_YellowLeaf__Curl_Virus',...
                    'Tomato_Bacterial_spot',...
                    'Tomato_healthy'};

    
            values_En = {struct('English',['Bacterial spot (Pepper):'...
                                '\n\t️️️️️️️️️️️➡️Small, dark brown spots: Look for these spots on leaves and fruit. They may be surrounded by a yellow halo.'...
                                '\n\t➡️Water-soaked lesions: These sunken areas may appear on leaves and stems.'...
                                '\n\t➡️Wilting and defoliation: In severe cases, leaves may wilt and fall off, affecting fruit production.']),...
            struct('English',['Healthy pepper plant:'...
                                '\n\t➡️Clean leaves: No spots or lesions should be visible on the leaves.'...
                                '\n\t➡️Upright stems: The stems should be strong and not wilting.'...
                                '\n\t➡️Good fruit development: Look for healthy, developing peppers without blemishes.']),...
            struct('English',['Early blight (Potato):'...
                                '\n\t➡️Concentric rings on leaves: Look for dark, brown rings getting progressively lighter towards the center.'...
                                '\n\t➡️Shot holes: The centers of the brown rings may develop into holes in leaves.'...
                                '\n\t➡️Stunted growth: Early blight can slow down potato plant growth and reduce yields.']),...
            struct('English',['Healthy potato plant:'...
                                '\n\t➡️Green, healthy leaves: No spots or lesions should be present on the leaves.'...
                                '\n\t➡️Strong stems: The stems should be upright and not wilting.'...
                                '\n\t➡️Healthy growth: The plant should be growing steadily with no signs of stunted development.']),...
            struct('English',['Late blight (Potato):'...
                                '\n\t➡️Water-soaked lesions: Look for dark, wet-looking areas on leaves and stems.'...
                                '\n\t➡️Rapid spread: Late blight can quickly spread throughout a potato field.'...
                                '\n\t➡️Blight on tubers: In severe cases, the disease can infect the developing potatoes underground.']),...
            struct('English',['Early blight (Tomato):'...
                                '\n\t➡️Concentric rings on leaves: Similar to potato early blight, look for dark brown rings with lighter centers.'...
                                '\n\t➡️Leaf drop: As the disease progresses, leaves with blight may fall off.'...
                                '\n\t➡️Reduced fruit production: Early blight can affect the overall yield of tomatoes.']),...
            struct('English',['Late blight (Tomato):'...
                                '\n\t➡️Water-soaked lesions: Look for dark, wet-looking areas on leaves, stems, and fruit.'...
                                '\n\t➡️Rapid spread: Like potato late blight, this disease can quickly spread throughout a tomato field.'...
                                '\n\t➡️Fruit rot: Late blight can cause infected tomatoes to rot and become unusable.']),...
            struct('English',['Leaf mold (Tomato):'...
                                '\n\t➡️Yellow patches: Initially, the leaves develop yellow patches.'...
                                '\n\t➡️Brown spots: As the disease progresses, the yellow patches turn brown and may cover larger areas.'...
                                '\n\t➡️Reduced fruit quality: Leaf mold can affect the overall health and quality of the developing tomatoes.']),...
            struct('English',['Septoria leaf spot (Tomato):'...
                                '\n\t➡️Small, dark spots: Look for these spots on leaves, with a yellow halo around them.'...
                                '\n\t➡️Shot holes: The centers of the dark spots may develop into holes, creating a “shot-hole” effect.'...
                                '\n\t➡️Defoliation: In severe cases, heavy leaf loss can occur due to extensive infection.']),...
            struct('English',['Spider mites (Tomato):'...
                                '\n\t➡️Yellow stippling: Look for a yellow, speckled appearance on the upper surface of leaves.'...
                                '\n\t➡️Webbing: Spider mites create fine webs on the underside of leaves.'...
                                '\n\t➡️Leaf drop: Heavy mite infestations can cause leaves to wilt and fall off.']),...
            struct('English',['Target spot (Tomato):'...
                                '\n\t➡️Concentric circles: Look for dark, brown circles with lighter centers on leaves and stems.'...
                                '\n\t➡️Bulls-eye pattern: The concentric circles may resemble a bulls-eye target.'...
                                '\n\t➡️Leaf drop: Severely infected leaves may drop prematurely.']),...
            struct('English',['Tomato mosaic virus:'...
                                '\n\t➡️Distorted leaves: The leaves become misshapen and develop a mosaic pattern of light and dark green areas.'...
                                '\n\t➡️Stunted growth: The virus can slow down the growth of the tomato plant.'...
                                '\n\t➡️Reduced fruit yield: The overall production of tomatoes may be significantly reduced.']),...
            struct('English',['Tomato yellow leaf curl virus:'...
                                '\n\t➡️Yellowing and curling: Leaves turn yellow and curl upwards at the edges.'...
                                '\n\t➡️Brittle leaves: Affected leaves become brittle and may crumble easily.'...
                                '\n\t➡️Stunted growth: Similar to tomato mosaic virus, this virus can stunt the growth of the plant.']),...
            struct('English',['Tomato Bacterial spot:'...
                                '\n\t➡️Small, dark brown spots: Look for these spots on leaves, stems, and fruit.'...
                                '\n\t➡️Water-soaked lesions: These sunken areas may appear on leaves and stems.'...
                                '\n\t➡️Wilting and defoliation: In severe cases, leaves may wilt and fall off, affecting fruit production.']),...
            struct('English',['Healthy Tomato Plant:'...
                                '\n\t➡️Green, healthy leaves: No spots or lesions should be present on the leaves.'...
                                '\n\t➡️Upright stems: The stems should be strong and not wilting.'...
                                '\n\t➡️Good fruit development: Look for healthy, developing tomatoes without blemishes.'])};


            values_Ro = {struct('Romanian',['Pătarea bacteriană a ardeiului (Pepper):'...
                                '\n\t➡️Mici pete maro închis: Căutați aceste pete pe frunze și fructe. Acestea pot fi înconjurate de un halo galben.'...
                                '\n\t➡️Leziuni înfundate în apă: Aceste zone adâncite pot apărea pe frunze și tulpini.'...
                                '\n\t➡️Ofilire și defoliere: În cazuri severe, frunzele pot ofili și cădea, afectând producția de fructe.']),...
            struct('Romanian',['Ardei gras sănătos:'...
                                '\n\t➡️Frunze curate: Nu ar trebui să fie vizibile pete sau leziuni pe frunze.'...
                                '\n\t➡️Tulpini drepte: Tulpinile ar trebui să fie puternice și să nu ofilească.'...
                                '\n\t➡️Dezvoltare bună a fructelor: Căutați ardei sănătoși, în dezvoltare, fără pete.']),...
            struct('Romanian',['Alternarioza la cartof:'...
                                '\n\t➡️Inele concentrice pe frunze: Căutați inele maro întunecate care devin progresiv mai ușoare spre centru.'...
                                '\n\t➡️Găuri de împușcare: Centrele inelelor maro pot deveni găuri în frunze.'...
                                '\n\t➡️Creștere împiedicată: Alternarioza precoce poate încetini creșterea plantelor de cartofi și reduce randamentele.']),...
            struct('Romanian',['Cartof sănătos:'...
                                '\n\t➡️Frunze verzi și sănătoase: Nu ar trebui să fie prezente pete sau leziuni pe frunze.'...
                                '\n\t➡️Creștere sănătoasă: Planta ar trebui să crească constant, fără semne de dezvoltare împiedicată.'...
                                '\n\t➡️Tulpini puternice: Tulpinile ar trebui să fie verticale și să nu ofilească.']), ...
            struct('Romanian',['Mana cartofului:'...
                                '\n\t➡️Leziuni înfundate în apă: Căutați zone întunecate și ude pe frunze și tulpini.'...
                                '\n\t➡️Răspândire rapidă: Ciuperca târzie se poate răspândi rapid într-un câmp de cartofi.'...
                                '\n\t➡️Ciupercă pe tuberculi: În cazuri severe, boala poate infecta cartofii în curs de dezvoltare sub pământ.']),...
            struct('Romanian',['Alternarioza tomatelor:'...
                                '\n\t➡️Inele concentrice pe frunze: Similar cu alternarioza precoce a cartofilor, căutați inele maro întunecate cu centre mai ușoare.'...
                                '\n\t➡️Cădere de frunze: Pe măsură ce boala progresează, frunzele cu boli pot cădea.'...
                                '\n\t➡️Producție redusă de fructe: Alternarioza precoce poate afecta randamentul general al roșiilor.']),...
            struct('Romanian',['Mana tomatelor:'...
                                '\n\t➡️Leziuni înfundate în apă: Căutați zone întunecate și umede pe frunze, tulpini și fructe.'...
                                '\n\t➡️Răspândire rapidă: La fel ca la cartof, această boală se poate răspândi rapid într-un câmp de roșii.'...
                                '\n\t➡️Putrezirea fructelor: Mana târzie poate cauza roșiile infectate să putrezească și să devină inutilizabile.']),...
            struct('Romanian',['Pătarea cafenie a frunzelor de tomate (Fulgerarea tomatelor):'...
                                '\n\t➡️Petice galbene: Inițial, frunzele dezvoltă pete galbene.'...
                                '\n\t➡️Pete maro: Pe măsură ce boala progresează, petele galbene devin maro și pot acoperi zone mai mari.'...
                                '\n\t➡️Calitatea redusă a fructelor: Mana frunzelor poate afecta sănătatea generală și calitatea roșiilor în curs de dezvoltare.']),...
            struct('Romanian',['Septorioza tomatelor (Patarea neagră a frunzelor de tomate):'...
                                '\n\t➡️Mici pete întunecate: Căutați aceste pete pe frunze, cu un halo galben în jurul lor.'...
                                '\n\t➡️Găuri de împușcare: Centrele petelor întunecate pot deveni găuri, creând un efect de "gaură de împușcare".'...
                                '\n\t➡️Defoliere: În cazuri severe, poate apărea o pierdere mare de frunze din cauza unei infecții extinse.']),...
            struct('Romanian',['Păianjenul roșu comun (Păianjenul roșu al tomatelor):'...
                                '\n\t➡️Petice galbene: Căutați o aparență galbenă și punctată pe suprafața superioară a frunzelor.'...
                                '\n\t➡️Pânză: Păianjenii roșii creează pânze fine pe partea inferioară a frunzelor.'...
                                '\n\t➡️Cădere de frunze: Infestările masive cu păianjeni pot face ca frunzele să ofilească și să cadă.']),...
            struct('Romanian',['Pet-spot (Fulgerarea țintei a tomatelor):'...
                                '\n\t➡️Cercuri concentrice: Căutați cercuri întunecate, maro cu centre mai ușoare pe frunze și tulpini.'...
                                '\n\t➡️Model tip țintă: Cercurile concentrice pot semăna cu o țintă.'...
                                '\n\t➡️Cădere de frunze: Frunzele grav infectate pot cădea prematur.']),...
            struct('Romanian',['Virusul mozaicului tomatelor:'...
                                '\n\t➡️Frunze distorsionate: Frunzele devin deformate și dezvoltă un model de mozaic cu zone verzi și întunecate.'...
                                '\n\t➡️Creștere împiedicată: Virusul poate încetini creșterea plantei de tomate.'...
                                '\n\t➡️Randament redus al fructelor: Producția totală de roșii poate fi semnificativ redusă.']),...
            struct('Romanian',['Virusul încurlării frunzelor de tomată (Virusul încurlării galbene a frunzelor de tomată):'...
                                '\n\t➡️Galbenire și încurlare: Frunzele devin galbene și se încurcă în sus la margini.'...
                                '\n\t➡️Frunze casante: Frunzele afectate devin casante și se pot sfărâma ușor.'...
                                '\n\t➡️Creștere împiedicată: Asemănător cu virusul mozaicului tomatelor, acest virus poate împiedica creșterea plantei.']),...
            struct('Romanian',['Pătarea bacteriană a tomatelor:'...
                                '\n\t➡️Mici pete maro închis: Căutați aceste pete pe frunze, tulpini și fructe.'...
                                '\n\t➡️Leziuni înfundate în apă: Aceste zone adâncite pot apărea pe frunze și tulpini.'...
                                '\n\t➡️Ofilire și defoliere: În cazuri severe, frunzele pot ofili și cădea, afectând producția de fructe.']),...
            struct('Romanian',['Tomate sănătoase:'...
                                '\n\t➡️Frunze verzi și sănătoase: Nu ar trebui să fie prezente pete sau leziuni pe frunze.'...
                                '\n\t➡️Tulpini verticale: Tulpinile ar trebui să fie puternice și să nu ofilească.'...
                                '\n\t➡️Dezvoltare bună a fructelor: Căutați roșii sănătoase, în dezvoltare, fără pete.'])};
            
            diseaseDetails_En = containers.Map(keys, values_En);
            diseaseDetails_Ro = containers.Map(keys, values_Ro);
            
            defaultDetails = struct('English', 'Details not available.', 'Romanian', 'Detalii indisponibile.');
            selectedLanguage = app.LanguageSwitch.Value;
            % Display the details in a message box based on the selected language
            if strcmp(selectedLanguage, 'ENG')
                diseaseDetails = diseaseDetails_En;
            elseif strcmp(selectedLanguage, 'RO')
                diseaseDetails = diseaseDetails_Ro;
            else
                details = defaultDetails;
                return;
            end
            % Check if the disease name exists in the map
            if isKey(diseaseDetails, disease)
                details = diseaseDetails(disease);
            else
                details = defaultDetails;
            end
        end
 

        function TreatmentOptions(app)
            if ~isempty(app.CurrentDiseaseEnglish)
                % Get the details for the current disease
                disease = app.CurrentDiseaseEnglish; % Assuming this is the disease name
                treatment = app.getTreatmentOptions(disease);

                % Check the selected language
                selectedLanguage = app.LanguageSwitch.Value;

                % Display the details in a message box based on the selected language
                if strcmp(selectedLanguage, 'ENG')
                    message = strrep(treatment.English, '\n\t', newline + "    ");
                elseif strcmp(selectedLanguage, 'RO')
                    message = strrep(treatment.Romanian, '\n\t', newline + "    ");
                else
                    message = 'Language not supported.';
                end

                % Display the details in a message box
                uialert(app.DiseaseDetectionUIFigure, message, 'Treatment Options', 'Icon', 'success');
            else
                % If no disease is detected, show a message
                uialert(app.DiseaseDetectionUIFigure, 'No disease detected.', 'No Disease', 'Icon', 'success');
            end
        end


        function treatment = getTreatmentOptions(app, disease)
            keys_Treatment = {'Pepper__bell___Bacterial_spot', ...
                    'Pepper__bell___healthy', ...
                    'Potato___Early_blight', ...
                    'Potato___healthy', ...
                    'Potato___Late_blight', ...
                    'Tomato_Early_blight', ...
                    'Tomato_Late_blight', ...
                    'Tomato_Leaf_Mold', ...
                    'Tomato_Septoria_leaf_spot', ...
                    'Tomato_Spider_mites_Two_spotted_spider_mite', ...
                    'Tomato__Target_Spot', ...
                    'Tomato__Tomato_mosaic_virus', ...
                    'Tomato__Tomato_YellowLeaf__Curl_Virus', ...
                    'Tomato_Bacterial_spot', ...
                    'Tomato_healthy'};

           values_En_Treatment = {struct('English', [...
                    'Bacterial spot (Pepper):'...
                    '\n\t➡️Apply copper-based fungicides.'...
                    '\n\t➡️Remove infected plant material.'...
                    '\n\t➡️Practice crop rotation.'...
                    '\n\t➡️Ensure proper spacing between plants.'...
                    '\n\t➡️Avoid overhead irrigation.']),...
                struct('English', [...
                    'Healthy pepper plant:'...
                    '\n\t➡️Maintain good soil moisture.'...
                    '\n\t➡️Use disease-free seeds and plants.'...
                    '\n\t➡️Apply balanced fertilizers.'...
                    '\n\t➡️Monitor for pests and diseases regularly.']),...
                struct('English', [...
                    'Early blight (Potato):'...
                    '\n\t➡️Remove infected leaves and stems.'...
                    '\n\t➡️Apply fungicides containing chlorothalonil.'...
                    '\n\t➡️Avoid overhead watering.'...
                    '\n\t➡️Practice crop rotation.'...
                    '\n\t➡️Apply mulch to prevent soil splashing.']),...
                struct('English', [...
                    'Healthy potato plant:'...
                    '\n\t➡️Plant disease-resistant potato varieties.'...
                    '\n\t➡️Ensure proper spacing between plants.'...
                    '\n\t➡️Use clean seed potatoes.'...
                    '\n\t➡️Practice crop rotation.'...
                    '\n\t➡️Inspect plants regularly for signs of disease.']),...
                struct('English', [...
                    'Late blight (Potato):'...
                    '\n\t➡️Apply fungicides containing chlorothalonil or mancozeb.'...
                    '\n\t➡️Remove and destroy infected plants.'...
                    '\n\t➡️Avoid overhead watering.'...
                    '\n\t➡️Practice crop rotation.'...
                    '\n\t➡️Harvest potatoes promptly.']),...
                struct('English', [...
                    'Early blight (Tomato):'...
                    '\n\t➡️Apply copper-based fungicides.'...
                    '\n\t➡️Remove and destroy infected leaves.'...
                    '\n\t➡️Mulch to prevent soil splashing.'...
                    '\n\t➡️Stake or cage plants for better air circulation.'...
                    '\n\t➡️Water at the base of plants.']),...
                struct('English', [...
                    'Late blight (Tomato):'...
                    '\n\t➡️Apply fungicides containing chlorothalonil or copper.'...
                    '\n\t➡️Remove infected leaves and stems.'...
                    '\n\t➡️Avoid overhead watering.'...
                    '\n\t➡️Improve air circulation around plants.'...
                    '\n\t➡️Destroy infected plant debris.']),...
                struct('English', [...
                    'Leaf mold (Tomato):'...
                    '\n\t➡️Increase air circulation around plants.'...
                    '\n\t➡️Water at the base of plants.'...
                    '\n\t➡️Use drip irrigation to keep foliage dry.'...
                    '\n\t➡️Apply fungicides containing chlorothalonil.'...
                    '\n\t➡️Remove infected leaves.']),...
                struct('English', [...
                    'Septoria leaf spot (Tomato):'...
                    '\n\t➡️Apply copper-based fungicides.'...
                    '\n\t➡️Remove and destroy infected leaves.'...
                    '\n\t➡️Avoid overhead watering.'...
                    '\n\t➡️Prune lower leaves for better air circulation.'...
                    '\n\t➡️Water at the base of plants.']),...
                struct('English', [...
                    'Spider mites (Tomato):'...
                    '\n\t➡️Spray with insecticidal soap or neem oil.'...
                    '\n\t➡️Increase humidity to discourage mites.'...
                    '\n\t➡️Remove heavily infested leaves.'...
                    '\n\t➡️Use a strong jet of water to dislodge mites.'...
                    '\n\t➡️Introduce natural predators like ladybugs.']),...
                struct('English', [...
                    'Target spot (Tomato):'...
                    '\n\t➡️Apply copper-based fungicides.'...
                    '\n\t➡️Remove and destroy infected leaves.'...
                    '\n\t➡️Avoid overhead watering.'...
                    '\n\t➡️Stake or cage plants for better air circulation.'...
                    '\n\t➡️Water at the base of plants.']),...
                struct('English', [...
                    'Tomato mosaic virus:'...
                    '\n\t➡️Remove and destroy infected plants.'...
                    '\n\t➡️Use disease-free seeds and plants.'...
                    '\n\t➡️Control aphid populations to prevent spread.'...
                    '\n\t➡️Avoid smoking near tomato plants.'...
                    '\n\t➡️Disinfect tools to prevent transmission.']),...
                struct('English', [...
                    'Tomato yellow leaf curl virus:'...
                    '\n\t➡️Plant virus-resistant tomato varieties.'...
                    '\n\t➡️Use reflective mulch to deter whiteflies.'...
                    '\n\t➡️Apply insecticides to control whiteflies.'...
                    '\n\t➡️Remove and destroy infected plants.'...
                    '\n\t➡️Control weeds to reduce whitefly habitat.']),...
                struct('English', [...
                    'Tomato Bacterial spot:'...
                    '\n\t➡️Apply copper-based bactericides.'...
                    '\n\t➡️Remove and destroy infected leaves.'...
                    '\n\t➡️Avoid overhead watering.'...
                    '\n\t➡️Improve air circulation around plants.'...
                    '\n\t➡️Use disease-free seeds and plants.']),...
                struct('English', [...
                    'Healthy Tomato Plant:'...
                    '\n\t➡️Maintain good soil moisture.'...
                    '\n\t➡️Use balanced fertilizers.'...
                    '\n\t➡️Monitor for pests and diseases regularly.'...
                    '\n\t➡️Prune plants for better air circulation.'...
                    '\n\t➡️Use mulch to retain moisture and suppress weeds.'])};


          values_Ro_Treatment = {struct('Romanian', [...
                'Tratament pentru Bacterial spot (Pepper):'...
                '\n\t➡️Aplicați fungicide pe bază de cupru.'...
                '\n\t➡️Îndepărtați materialul vegetal infectat.'...
                '\n\t➡️Practicați rotația culturilor.'...
                '\n\t➡️Asigurați un spațiu adecvat între plante.'...
                '\n\t➡️Evitați udarea deasupra plantelor.']),...
            struct('Romanian', [...
                'Ardei gras: sănătos:'...
                '\n\t➡️Mențineți umiditatea solului adecvată.'...
                '\n\t➡️Folosiți semințe și plante lipsite de boli.'...
                '\n\t➡️Aplicați îngrășăminte echilibrate.'...
                '\n\t➡️Monitorizați regulat pentru dăunători și boli.']),...
            struct('Romanian', [...
                'Tratament pentru Alternarioza precoce a cartofului:'...
                '\n\t➡️Îndepărtați frunzele și tulpinile infectate.'...
                '\n\t➡️Aplicați fungicide care conțin clorotalonil.'...
                '\n\t➡️Evitați udarea deasupra plantei.'...
                '\n\t➡️Practicați rotația culturilor.'...
                '\n\t➡️Aplicați mulci pentru a preveni stropirea solului.']),...
            struct('Romanian', [...
                'Cartof sănătos:'...
                '\n\t➡️Plantați soiuri de cartofi rezistente la boli.'...
                '\n\t➡️Asigurați un spațiu adecvat între plante.'...
                '\n\t➡️Folosiți cartofi sănătoși pentru sămânță.'...
                '\n\t➡️Practicați rotația culturilor.'...
                '\n\t➡️Inspectați plantele în mod regulat pentru semne de boală.']),...
            struct('Romanian', [...
                'Tratament pentru Ciuperca târzie a cartofului:'...
                '\n\t➡️Aplicați fungicide care conțin clorotalonil sau mancozeb.'...
                '\n\t➡️Îndepărtați și distrugeți plantele infectate.'...
                '\n\t➡️Evitați udarea deasupra plantei.']),...
            struct('Romanian', [...
                'Tratament pentru Alternarioza tomatelor:'...
                '\n\t➡️Aplicați fungicide care conțin clorotalonil sau mancozeb.'...
                '\n\t➡️Îndepărtați și distrugeți plantele infectate.'...
                '\n\t➡️Asigurați un spațiu adecvat între plante.'...
                '\n\t➡️Folosiți mulci pentru a reduce stropirea solului.'...
                '\n\t➡️Evitați udarea frunzelor.'...
                '\n\t➡️Rotați culturile pentru a preveni infestările recurente.']),...
            struct('Romanian', [...
                'Tratament pentru Mana tomatelor:'...
                '\n\t➡️Aplicați fungicide cu cupru sau mancozeb.'...
                '\n\t➡️Eliminați plantele infectate pentru a preveni răspândirea.'...
                '\n\t➡️Asigurați o circulație bună a aerului în jurul plantelor.'...
                '\n\t➡️Evitați udarea excesivă a frunzelor.'...
                '\n\t➡️Rotați culturile și practicați igiena grădinii.']),...
            struct('Romanian', [...
                'Tratament pentru Patarea cafenie a frunzelor de tomate:'...
                '\n\t➡️Aplicați fungicide cu cupru sau mancozeb.'...
                '\n\t➡️Îndepărtați frunzele infectate.'...
                '\n\t➡️Asigurați o circulație bună a aerului în jurul plantelor.'...
                '\n\t➡️Evitați udarea excesivă a frunzelor.'...
                '\n\t➡️Folosiți mulci pentru a preveni stropirea solului.']),...
            struct('Romanian', [...
                'Tratament pentru Septorioza tomatelor:'...
                '\n\t➡️Aplicați fungicide care conțin clorotalonil sau mancozeb.'...
                '\n\t➡️Îndepărtați frunzele infectate.'...
                '\n\t➡️Asigurați un spațiu adecvat între plante pentru o bună circulație a aerului.'...
                '\n\t➡️Evitați umezeala excesivă pe frunze.'...
                '\n\t➡️Folosiți mulci pentru a preveni răspândirea sporilor.']),...
            struct('Romanian', [...
                'Tratament pentru Paianjenul rosu comun (Tomate):'...
                '\n\t➡️Aplicați acaricide pentru a controla păianjenii roșii.'...
                '\n\t➡️Îndepărtați și distrugeți plantele afectate.'...
                '\n\t➡️Asigurați o umiditate mai ridicată pentru a descuraja păianjenii.'...
                '\n\t➡️Folosiți plante de capcană pentru a atrage și captura păianjenii.'...
                '\n\t➡️Rotați culturile și mențineți igiena grădinii.']),...
            struct('Romanian', [...
                'Tratament pentru Patarea țintită la roșii:'...
                '\n\t➡️Aplicați fungicide care conțin clorotalonil sau mancozeb.'...
                '\n\t➡️Îndepărtați plantele afectate și distrugeți-le.'...
                '\n\t➡️Evitați irigarea frunzelor.'...
                '\n\t➡️Asigurați o bună circulație a aerului în jurul plantelor.'...
                '\n\t➡️Practicați igiena grădinii și rotația culturilor.']),...
            struct('Romanian', [...
                'Tratament pentru Virusul mozaicului tomatelor:'...
                '\n\t➡️Nu există tratament specific pentru virusul mozaicului.'...
                '\n\t➡️Îndepărtați și distrugeți plantele afectate pentru a preveni răspândirea.'...
                '\n\t➡️Folosiți plante sănătoase și semințe certificate.'...
                '\n\t➡️Controlați dăunătorii care pot răspândi virusul.'...
                '\n\t➡️Practicați igiena grădinii și rotația culturilor.']),...
            struct('Romanian', [...
                'Tratament pentru Virusul de încovoiere a frunzelor de tomată:'...
                '\n\t➡️Nu există tratament specific pentru acest virus.'...
                '\n\t➡️Îndepărtați plantele afectate pentru a preveni răspândirea.'...
                '\n\t➡️Utilizați plante și semințe certificate sănătoase.'...
                '\n\t➡️Evitați udarea frunzelor.'...
                '\n\t➡️Controlați dăunătorii care pot răspândi virusul.']),...
            struct('Romanian', [...
                'Tratament pentru Patarea bacteriană a tomatelor:'...
                '\n\t➡️Nu există tratament specific pentru această boală.'...
                '\n\t➡️Îndepărtați plantele infectate pentru a preveni răspândirea.'...
                '\n\t➡️Evitați udarea frunzelor și a tulpinilor.'...
                '\n\t➡️Folosiți plante sănătoase și semințe certificate.'...
                '\n\t➡️Practicați igiena grădinii și rotația culturilor.']),...
            struct('Romanian', [...
                'Tomata sănătoasă:'...
                '\n\t➡️Asigurați un sol bine drenat și o umiditate adecvată.'...
                '\n\t➡️Folosiți semințe și plante sănătoase, certificate.'...
                '\n\t➡️Practicați rotația culturilor.'...
                '\n\t➡️Asigurați o circulație bună a aerului în jurul plantelor.'...
                '\n\t➡️Monitorizați și controlați dăunătorii și bolile.'])};
    
            
            treatmentOptions_En = containers.Map(keys_Treatment, values_En_Treatment);
            treatmentOptions_Ro = containers.Map(keys_Treatment, values_Ro_Treatment);
            
            defaultTreatment = struct('English', 'Treatment not available.', 'Romanian', 'Tratament indisponibil.');
            selectedLanguage = app.LanguageSwitch.Value;
            % Display the details in a message box based on the selected language
            if strcmp(selectedLanguage, 'ENG')
                treatmentOptions = treatmentOptions_En;
            elseif strcmp(selectedLanguage, 'RO')
                treatmentOptions = treatmentOptions_Ro;
            else
                treatment = defaultTreatment;
                return;
            end

            % Check if the disease name exists in the map
            % Check if the disease name exists in the map
            if isKey(treatmentOptions, disease)
                treatment = treatmentOptions(disease);
            else
                treatment = defaultTreatment;
            end
        end
    end


    % App creation and deletion
    methods (Access = public)

        % Construct app
        function app = App
            % Create UIFigure and components
            createComponents(app)
            % Register the app with App Designer
            registerApp(app, app.DiseaseDetectionUIFigure)
            
            % Mapam bolile
            englishNames = {'Pepper__bell___Bacterial_spot','Pepper__bell___healthy','Potato___Early_blight','Potato___healthy','Potato___Late_blight','Tomato_Early_blight','Tomato_Late_blight','Tomato_Leaf_Mold','Tomato_Septoria_leaf_spot','Tomato_Spider_mites_Two_spotted_spider_mite','Tomato__Target_Spot','Tomato__Tomato_mosaic_virus','Tomato__Tomato_YellowLeaf__Curl_Virus','Tomato_Bacterial_spot','Tomato_healthy'};
            romanianNames = {'Pătarea frunzelor și bășicarea fructelor de ardei','Ardei gras sanatos','Alternarioza la cartof','Cartof sănătos','Ciuperca Cartofului','Alternarioza tomatelor','Mana tomatelor','Pătarea cafenie a frunzelor de tomate','Septorioza tomatelor','Paianjenul roșu comun','Pătarea brună a frunzelor de tomate','Mozaicul tomatelor','Virusul îngălbenirii și răsucirii frunzelor de tomate','Pătarea frunzelor și bășicarea fructelor tomatelor','Tomate sănătoase'};
            app.DiseaseNameMapping = containers.Map(englishNames, romanianNames);
        end

        % Code that executes before app deletion
        function delete(app)
            % Delete UIFigure when app is deleted
            delete(app.DiseaseDetectionUIFigure)
        end
    end
end