classdef App < matlab.apps.AppBase

    % Properties that correspond to app components
    properties (Access = public)
        DiseaseDetectionUIFigure  matlab.ui.Figure
        BackgroundPanel           matlab.ui.container.Panel
        BackgroundAxes            matlab.ui.control.UIAxes
        TextArea                  matlab.ui.control.TextArea
        InsertPictureButton       matlab.ui.control.Button
        LanguageSwitch            matlab.ui.control.Switch
        InsertedImage             matlab.ui.control.Image
        PredictedPlantLabel       matlab.ui.control.Label
        DiseaseDetailsButton      matlab.ui.control.Button
        TreatmentOptionsButton    matlab.ui.control.Button
        DiseaseNameMapping        containers.Map
        CurrentDiseaseEnglish     string
    end

    % Component initialization
    % Component initialization
    methods (Access = private)

    % Create UIFigure and components
    function createComponents(app)

        % Create DiseaseDetectionUIFigure
        app.DiseaseDetectionUIFigure = uifigure('Name', 'Disease Detection');
        app.DiseaseDetectionUIFigure.Position = [100 100 800 600]; % Set the figure position

        % Create BackgroundPanel
        app.BackgroundPanel = uipanel(app.DiseaseDetectionUIFigure);
        app.BackgroundPanel.BackgroundColor = [255/255, 228/255, 181/255];
        app.BackgroundPanel.Position = [1,1,834,604]; % Adjust the panel size

        % Create BackgroundAxes
        app.BackgroundAxes = uiaxes(app.BackgroundPanel);
        app.BackgroundAxes.Position = [1,1,834,604]; % Adjust the axes size
        imshow("D:\Downloads\imaginefundal.jpg", 'Parent', app.BackgroundAxes); % Set background image here
        app.BackgroundAxes.XTick = [];
        app.BackgroundAxes.YTick = [];
        app.BackgroundAxes.Box = 'off';

        % Create TextArea
        app.TextArea = uitextarea(app.DiseaseDetectionUIFigure);
        app.TextArea.Position = [320 510 160 35]; % Adjust position of TextArea
        app.TextArea.Value = {'  Choose the picture required for the inspection'};
        app.TextArea.Editable = false; % Make the text non-editable

        % Create InsertPictureButton
        app.InsertPictureButton = uibutton(app.DiseaseDetectionUIFigure, 'push');
        app.InsertPictureButton.Position = [320 470 160 35]; % Adjust position of InsertPictureButton
        app.InsertPictureButton.Text = 'Insert Picture';
        app.InsertPictureButton.ButtonPushedFcn = @(src, event) insertPictureButtonPushed(app);

        % Create LanguageSwitch
        app.LanguageSwitch = uiswitch(app.DiseaseDetectionUIFigure, 'slider');
        app.LanguageSwitch.Items = {'ENG', 'RO'};
        app.LanguageSwitch.Position = [50, 510, 50, 22]; % Adjust position of the switch button
        app.LanguageSwitch.ValueChangedFcn = @(src, event) switchLanguage(app, src, event);

        % Create PredictedPlantLabel
        app.PredictedPlantLabel = uilabel(app.DiseaseDetectionUIFigure);
        app.PredictedPlantLabel.Position = [320 440 400 22]; % Adjust position of PredictedPlantLabel
        app.PredictedPlantLabel.Text = '';

        % Create DiseaseDetailsButton
        app.DiseaseDetailsButton = uibutton(app.DiseaseDetectionUIFigure, 'push');
        app.DiseaseDetailsButton.Position = [320, 200, 160, 35]; % Adjust position of DiseaseDetailsButton
        app.DiseaseDetailsButton.Text = 'Disease Details';
        app.DiseaseDetailsButton.ButtonPushedFcn = @(src, event) DiseaseDetails(app);
        app.DiseaseDetailsButton.Visible = 'off'; % Set the button to be visible

        % Create TreatmentOptions Button
        app.TreatmentOptionsButton = uibutton(app.DiseaseDetectionUIFigure, 'push');
        app.TreatmentOptionsButton.Position = [320, 100, 160, 35];
        app.TreatmentOptionsButton.Text = 'Treatment Options';
        app.TreatmentOptionsButton.ButtonPushedFcn = @(src, event) TreatmentOptions(app);
        app.TreatmentOptionsButton.Visible = 'off'; % Set the button to be visible

        % Show the figure after all components are created
        app.DiseaseDetectionUIFigure.Visible = 'on';
    end


        % Function to add a border to an image
        function imgWithBorderPath = addImageBorder(~, imgPath, borderColor, borderWidth)
            img = imread(imgPath);
            % Create a border around the image
            border = uint8(ones(size(img, 1) + 2 * borderWidth, size(img, 2) + 2 * borderWidth, size(img, 3)) * 255);
            for c = 1:3
                border(:,:,c) = borderColor(c);
            end
            border(borderWidth+1:end-borderWidth, borderWidth+1:end-borderWidth, :) = img;
            % Convert the image with border to a format that can be used in the app
            imgWithBorderPath = [tempname, '.png'];
            imwrite(border, imgWithBorderPath);
        end

        function updateDiseaseLabelLanguage(app, language)
            % Check if the PredictedPlantLabel object exists and is valid
            if isempty(app.PredictedPlantLabel) || ~isvalid(app.PredictedPlantLabel)
                % If the label does not exist or is not valid, exit the function
                return;
            end
    
            % Now check if CurrentDiseaseEnglish has a valid value
            if isempty(app.CurrentDiseaseEnglish) || (~ischar(app.CurrentDiseaseEnglish) && ~isstring(app.CurrentDiseaseEnglish))
                % If there's no disease detected yet or the format is incorrect, exit the function
                return;
            end

            % Update the label based on the current language setting
            if language == "ENG"
                formattedLabel = strrep(app.CurrentDiseaseEnglish, '_', ' ');
                app.PredictedPlantLabel.Text = formattedLabel;
            elseif language == "RO"
                if isKey(app.DiseaseNameMapping, char(app.CurrentDiseaseEnglish))
                    app.PredictedPlantLabel.Text = app.DiseaseNameMapping(char(app.CurrentDiseaseEnglish));
                else
                    app.PredictedPlantLabel.Text = 'Boală necunoscută'; % Placeholder text for unknown disease
                end
            end
        end


         function insertPictureButtonPushed(app)
            % Open file explorer to select an image
            [fileName, pathName] = uigetfile({'*.jpg;*.jpeg;*.png'}, 'Select an image');
            if ~isequal(fileName, 0)
                % Clear the previous background image
                cla(app.BackgroundAxes); % Clear the current axes
                app.BackgroundAxes.Visible = 'on';
                app.BackgroundAxes.Color = [255/255, 228/255, 181/255];
                app.BackgroundAxes.Box = 'off';
                app.BackgroundAxes.XColor = 'none';
                app.BackgroundAxes.YColor = 'none'; 
                app.BackgroundAxes.XTick = [];
                app.BackgroundAxes.YTick = [];
        
                % Load pre-trained GoogLeNet
                net1 = googlenet;
                targetSize = net1.Layers(1).InputSize;
        
                imagePath = fullfile(pathName, fileName);
                inputImage = imread(imagePath);
                resizedImage = imresize(inputImage, targetSize(1:2));
        
                % Load your models
                load('plant_disease_model.mat', 'convnet');
        
                % Classify the image with the models
                [predictedLabel1, scores1] = classify(convnet, resizedImage);
               
                % Set confidence threshold for plant disease classification
                confidenceThreshold = 0.79; % Adjust as needed
        
                % Check if the highest confidence score from either model is above the threshold
                if max(scores1) >= confidenceThreshold 
                    disp(['Predicted label using Model 1: ' char(predictedLabel1)]);
                else
                    disp('The provided image is not recognized as a plant disease.');
                end
        
                disp('Max score for Model 1:');
                disp(max(scores1));
                
        
                % Add a green border to the image and get the new image path
                imgWithBorderPath = app.addImageBorder(imagePath, [0, 155, 0], 10); % Green border with a width of 10 pixels
        
                % Display the image with border
                app.InsertedImage = uiimage(app.DiseaseDetectionUIFigure);
                app.InsertedImage.ImageSource = imgWithBorderPath;
                imgWidth = size(resizedImage, 2);
                imgHeight = size(resizedImage, 1);
                app.InsertedImage.Position = [(app.DiseaseDetectionUIFigure.Position(3) - imgWidth) / 2, (app.DiseaseDetectionUIFigure.Position(4) - imgHeight) / 2 + 170, imgWidth, imgHeight]; % Adjust position and size of the inserted image to account for the border
        
                % Update the text with the predicted plant label
                app.PredictedPlantLabel = uilabel(app.DiseaseDetectionUIFigure);
                app.PredictedPlantLabel.Position = [app.InsertedImage.Position(1) + 30, app.InsertedImage.Position(2) - 30, 400, 22]; % Adjust position of the label
                if max(scores1) >= confidenceThreshold 
                    app.CurrentDiseaseEnglish = char(predictedLabel1);
                    updateDiseaseLabelLanguage(app, app.LanguageSwitch.Value);
                else
                    app.CurrentDiseaseEnglish = 'No disease detected';
                    updateDiseaseLabelLanguage(app, app.LanguageSwitch.Value);
                end
        
                % Make the Disease Details Button visible after picture is classified
                app.DiseaseDetailsButton.Visible = 'on';
                app.TreatmentOptionsButton.Visible = 'on';
        
                % Hide unnecessary components
                app.TextArea.Visible = 'off';
            end
        end


        function switchLanguage(app, src, ~)
            % Get the current value of the switch button
            selectedLanguage = src.Value;

            % Update the text of the components based on the selected language
            if strcmp(selectedLanguage, 'ENG')
                app.TextArea.Value = {'  Choose the picture required for the inspection'};
                app.InsertPictureButton.Text = 'Insert Picture';
                app.DiseaseDetailsButton.Text = 'Disease Details';
                app.TreatmentOptionsButton.Text = 'Treatment Options';
                app.updateDiseaseLabelLanguage('ENG');
            elseif strcmp(selectedLanguage, 'RO')
                app.TextArea.Value = {'  Alegeți imaginea necesară pentru inspecție'};
                app.InsertPictureButton.Text = 'Inserați imaginea';
                app.DiseaseDetailsButton.Text = 'Detalii Boală';
                app.TreatmentOptionsButton.Text = 'Opțiuni de Tratament';
                app.updateDiseaseLabelLanguage('RO');
            end

            % Update the LanguageSwitch component text
            app.LanguageSwitch.Items = {'ENG', 'RO'}; % Update language options
        end
    
    

        function DiseaseDetails(app)
            % Check if there is a currently detected disease
            if ~isempty(app.CurrentDiseaseEnglish)
                % Get the details for the current disease
                disease = app.CurrentDiseaseEnglish; % Assuming this is the disease name
                details = app.getDiseaseDetails(disease);

                % Check the selected language
                selectedLanguage = app.LanguageSwitch.Value;

                % Display the details in a message box based on the selected language
                if strcmp(selectedLanguage, 'ENG')
                    message = strrep(details.English, '\n\t', newline + "    ");
                elseif strcmp(selectedLanguage, 'RO')
                    message = strrep(details.Romanian, '\n\t', newline + "    ");
                else
                    message = 'Language not supported.';
                end

                % Display the details in a message box
                uialert(app.DiseaseDetectionUIFigure, message, 'Disease Details', 'Icon', 'info');
            else
                % If no disease is detected, show a message
                uialert(app.DiseaseDetectionUIFigure, 'No disease detected.', 'No Disease', 'Icon', 'info');
            end
        end

        function details = getDiseaseDetails(app, disease)
            % Define disease details based on the disease name
            keys = {'Pepper__bell___Bacterial_spot',...
                    'Pepper__bell___healthy',...
                    'Potato___Early_blight',...
                    'Potato___healthy',...
                    'Potato___Late_blight',...
                    'Tomato_Early_blight',...
                    'Tomato_Late_blight',...
                    'Tomato_Leaf_Mold',...
                    'Tomato_Septoria_leaf_spot',...
                    'Tomato_Spider_mites_Two_spotted_spider_mite',...
                    'Tomato__Target_Spot',...
                    'Tomato__Tomato_mosaic_virus',...
                    'Tomato__Tomato_YellowLeaf__Curl_Virus',...
                    'Tomato_Bacterial_spot',...
                    'Tomato_healthy'};

    
            values_En = {struct('English',['Bacterial spot (Pepper):'...
                                '\n\tSmall, dark brown spots: Look for these spots on leaves and fruit. They may be surrounded by a yellow halo.'...
                                '\n\tWater-soaked lesions: These sunken areas may appear on leaves and stems.'...
                                '\n\tWilting and defoliation: In severe cases, leaves may wilt and fall off, affecting fruit production.']),...
            struct('English',['Healthy pepper plant:'...
                                '\n\tClean leaves: No spots or lesions should be visible on the leaves.'...
                                '\n\tUpright stems: The stems should be strong and not wilting.'...
                                '\n\tGood fruit development: Look for healthy, developing peppers without blemishes.']),...
            struct('English',['Early blight (Potato):'...
                                '\n\tConcentric rings on leaves: Look for dark, brown rings getting progressively lighter towards the center.'...
                                '\n\tShot holes: The centers of the brown rings may develop into holes in leaves.'...
                                '\n\tStunted growth: Early blight can slow down potato plant growth and reduce yields.']),...
            struct('English',['Healthy potato plant:'...
                                '\n\tGreen, healthy leaves: No spots or lesions should be present on the leaves.'...
                                '\n\tStrong stems: The stems should be upright and not wilting.'...
                                '\n\tHealthy growth: The plant should be growing steadily with no signs of stunted development.']),...
            struct('English',['Late blight (Potato):'...
                                '\n\tWater-soaked lesions: Look for dark, wet-looking areas on leaves and stems.'...
                                '\n\tRapid spread: Late blight can quickly spread throughout a potato field.'...
                                '\n\tBlight on tubers: In severe cases, the disease can infect the developing potatoes underground.']),...
            struct('English',['Early blight (Tomato):'...
                                '\n\tConcentric rings on leaves: Similar to potato early blight, look for dark brown rings with lighter centers.'...
                                '\n\tLeaf drop: As the disease progresses, leaves with blight may fall off.'...
                                '\n\tReduced fruit production: Early blight can affect the overall yield of tomatoes.']),...
            struct('English',['Late blight (Tomato):'...
                                '\n\tWater-soaked lesions: Look for dark, wet-looking areas on leaves, stems, and fruit.'...
                                '\n\tRapid spread: Like potato late blight, this disease can quickly spread throughout a tomato field.'...
                                '\n\tFruit rot: Late blight can cause infected tomatoes to rot and become unusable.']),...
            struct('English',['Leaf mold (Tomato):'...
                                '\n\tYellow patches: Initially, the leaves develop yellow patches.'...
                                '\n\tBrown spots: As the disease progresses, the yellow patches turn brown and may cover larger areas.'...
                                '\n\tReduced fruit quality: Leaf mold can affect the overall health and quality of the developing tomatoes.']),...
            struct('English',['Septoria leaf spot (Tomato):'...
                                '\n\tSmall, dark spots: Look for these spots on leaves, with a yellow halo around them.'...
                                '\n\tShot holes: The centers of the dark spots may develop into holes, creating a “shot-hole” effect.'...
                                '\n\tDefoliation: In severe cases, heavy leaf loss can occur due to extensive infection.']),...
            struct('English',['Spider mites (Tomato):'...
                                '\n\tYellow stippling: Look for a yellow, speckled appearance on the upper surface of leaves.'...
                                '\n\tWebbing: Spider mites create fine webs on the underside of leaves.'...
                                '\n\tLeaf drop: Heavy mite infestations can cause leaves to wilt and fall off.']),...
            struct('English',['Target spot (Tomato):'...
                                '\n\tConcentric circles: Look for dark, brown circles with lighter centers on leaves and stems.'...
                                '\n\tBulls-eye pattern: The concentric circles may resemble a bulls-eye target.'...
                                '\n\tLeaf drop: Severely infected leaves may drop prematurely.']),...
            struct('English',['Tomato mosaic virus:'...
                                '\n\tDistorted leaves: The leaves become misshapen and develop a mosaic pattern of light and dark green areas.'...
                                '\n\tStunted growth: The virus can slow down the growth of the tomato plant.'...
                                '\n\tReduced fruit yield: The overall production of tomatoes may be significantly reduced.']),...
            struct('English',['Tomato yellow leaf curl virus:'...
                                '\n\tYellowing and curling: Leaves turn yellow and curl upwards at the edges.'...
                                '\n\tBrittle leaves: Affected leaves become brittle and may crumble easily.'...
                                '\n\tStunted growth: Similar to tomato mosaic virus, this virus can stunt the growth of the plant.']),...
            struct('English',['Tomato Bacterial spot:'...
                                '\n\tSmall, dark brown spots: Look for these spots on leaves, stems, and fruit.'...
                                '\n\tWater-soaked lesions: These sunken areas may appear on leaves and stems.'...
                                '\n\tWilting and defoliation: In severe cases, leaves may wilt and fall off, affecting fruit production.']),...
            struct('English',['Healthy Tomato Plant:'...
                                '\n\tGreen, healthy leaves: No spots or lesions should be present on the leaves.'...
                                '\n\tUpright stems: The stems should be strong and not wilting.'...
                                '\n\tGood fruit development: Look for healthy, developing tomatoes without blemishes.'])};


            values_Ro = {struct('Romanian',['Pătarea bacteriană a ardeiului (Pepper):'...
                                '\n\tMici pete maro închis: Căutați aceste pete pe frunze și fructe. Acestea pot fi înconjurate de un halo galben.'...
                                '\n\tLeziuni înfundate în apă: Aceste zone adâncite pot apărea pe frunze și tulpini.'...
                                '\n\tOfilire și defoliere: În cazuri severe, frunzele pot ofili și cădea, afectând producția de fructe.']),...
            struct('Romanian',['Ardei gras sănătos:'...
                                '\n\tFrunze curate: Nu ar trebui să fie vizibile pete sau leziuni pe frunze.'...
                                '\n\tTulpini drepte: Tulpinile ar trebui să fie puternice și să nu ofilească.'...
                                '\n\tDezvoltare bună a fructelor: Căutați ardei sănătoși, în dezvoltare, fără pete.']),...
            struct('Romanian',['Alternarioza la cartof:'...
                                '\n\tInele concentrice pe frunze: Căutați inele maro întunecate care devin progresiv mai ușoare spre centru.'...
                                '\n\tGăuri de împușcare: Centrele inelelor maro pot deveni găuri în frunze.'...
                                '\n\tCreștere împiedicată: Alternarioza precoce poate încetini creșterea plantelor de cartofi și reduce randamentele.']),...
            struct('Romanian',['Cartof sănătos:'...
                                '\n\tFrunze verzi și sănătoase: Nu ar trebui să fie prezente pete sau leziuni pe frunze.'...
                                '\n\tCreștere sănătoasă: Planta ar trebui să crească constant, fără semne de dezvoltare împiedicată.'...
                                '\n\tTulpini puternice: Tulpinile ar trebui să fie verticale și să nu ofilească.']), ...
            struct('Romanian',['Mana cartofului:'...
                                '\n\tLeziuni înfundate în apă: Căutați zone întunecate și ude pe frunze și tulpini.'...
                                '\n\tRăspândire rapidă: Ciuperca târzie se poate răspândi rapid într-un câmp de cartofi.'...
                                '\n\tCiupercă pe tuberculi: În cazuri severe, boala poate infecta cartofii în curs de dezvoltare sub pământ.']),...
            struct('Romanian',['Alternarioza tomatelor:'...
                                '\n\tInele concentrice pe frunze: Similar cu alternarioza precoce a cartofilor, căutați inele maro întunecate cu centre mai ușoare.'...
                                '\n\tCădere de frunze: Pe măsură ce boala progresează, frunzele cu boli pot cădea.'...
                                '\n\tProducție redusă de fructe: Alternarioza precoce poate afecta randamentul general al roșiilor.']),...
            struct('Romanian',['Mana tomatelor:'...
                                '\n\tLeziuni înfundate în apă: Căutați zone întunecate și umede pe frunze, tulpini și fructe.'...
                                '\n\tRăspândire rapidă: La fel ca la cartof, această boală se poate răspândi rapid într-un câmp de roșii.'...
                                '\n\tPutrezirea fructelor: Mana târzie poate cauza roșiile infectate să putrezească și să devină inutilizabile.']),...
            struct('Romanian',['Pătarea cafenie a frunzelor de tomate (Fulgerarea tomatelor):'...
                                '\n\tPetice galbene: Inițial, frunzele dezvoltă pete galbene.'...
                                '\n\tPete maro: Pe măsură ce boala progresează, petele galbene devin maro și pot acoperi zone mai mari.'...
                                '\n\tCalitatea redusă a fructelor: Mana frunzelor poate afecta sănătatea generală și calitatea roșiilor în curs de dezvoltare.']),...
            struct('Romanian',['Septorioza tomatelor (Patarea neagră a frunzelor de tomate):'...
                                '\n\tMici pete întunecate: Căutați aceste pete pe frunze, cu un halo galben în jurul lor.'...
                                '\n\tGăuri de împușcare: Centrele petelor întunecate pot deveni găuri, creând un efect de "gaură de împușcare".'...
                                '\n\tDefoliere: În cazuri severe, poate apărea o pierdere mare de frunze din cauza unei infecții extinse.']),...
            struct('Romanian',['Păianjenul roșu comun (Păianjenul roșu al tomatelor):'...
                                '\n\tPetice galbene: Căutați o aparență galbenă și punctată pe suprafața superioară a frunzelor.'...
                                '\n\tPânză: Păianjenii roșii creează pânze fine pe partea inferioară a frunzelor.'...
                                '\n\tCădere de frunze: Infestările masive cu păianjeni pot face ca frunzele să ofilească și să cadă.']),...
            struct('Romanian',['Pet-spot (Fulgerarea țintei a tomatelor):'...
                                '\n\tCercuri concentrice: Căutați cercuri întunecate, maro cu centre mai ușoare pe frunze și tulpini.'...
                                '\n\tModel tip țintă: Cercurile concentrice pot semăna cu o țintă.'...
                                '\n\tCădere de frunze: Frunzele grav infectate pot cădea prematur.']),...
            struct('Romanian',['Virusul mozaicului tomatelor:'...
                                '\n\tFrunze distorsionate: Frunzele devin deformate și dezvoltă un model de mozaic cu zone verzi și întunecate.'...
                                '\n\tCreștere împiedicată: Virusul poate încetini creșterea plantei de tomate.'...
                                '\n\tRandament redus al fructelor: Producția totală de roșii poate fi semnificativ redusă.']),...
            struct('Romanian',['Virusul încurlării frunzelor de tomată (Virusul încurlării galbene a frunzelor de tomată):'...
                                '\n\tGalbenire și încurlare: Frunzele devin galbene și se încurcă în sus la margini.'...
                                '\n\tFrunze casante: Frunzele afectate devin casante și se pot sfărâma ușor.'...
                                '\n\tCreștere împiedicată: Asemănător cu virusul mozaicului tomatelor, acest virus poate împiedica creșterea plantei.']),...
            struct('Romanian',['Pătarea bacteriană a tomatelor:'...
                                '\n\tMici pete maro închis: Căutați aceste pete pe frunze, tulpini și fructe.'...
                                '\n\tLeziuni înfundate în apă: Aceste zone adâncite pot apărea pe frunze și tulpini.'...
                                '\n\tOfilire și defoliere: În cazuri severe, frunzele pot ofili și cădea, afectând producția de fructe.']),...
            struct('Romanian',['Tomate sănătoase:'...
                                '\n\tFrunze verzi și sănătoase: Nu ar trebui să fie prezente pete sau leziuni pe frunze.'...
                                '\n\tTulpini verticale: Tulpinile ar trebui să fie puternice și să nu ofilească.'...
                                '\n\tDezvoltare bună a fructelor: Căutați roșii sănătoase, în dezvoltare, fără pete.'])};
            
            diseaseDetails_En = containers.Map(keys, values_En);
            diseaseDetails_Ro = containers.Map(keys, values_Ro);
            
            details = struct('English', 'Details not available.', 'Romanian', 'Detalii indisponibile.');
            selectedLanguage = app.LanguageSwitch.Value;
            % Display the details in a message box based on the selected language
            if strcmp(selectedLanguage, 'ENG')
                diseaseDetails = diseaseDetails_En;
            elseif strcmp(selectedLanguage, 'RO')
                diseaseDetails = diseaseDetails_Ro;
            else
                return;
            end
            % Check if the disease name exists in the map
            if isKey(diseaseDetails, disease)
                details = diseaseDetails(disease);
            end
            %if isstruct(details)
                %details = struct2cell(details);
                %details = strjoin(details,' ');
            %end
            %details = strrep(details, '\n', newline);
            %details = strrep(details, '\t', sprintf('\t'));
            
        end
 
        function TreatmentOptions(app)
        if ~isempty(app.CurrentDiseaseEnglish)
                % Get the details for the current disease
                disease = app.CurrentDiseaseEnglish; % Assuming this is the disease name
                treatment = app.getTreatmentOptions(disease);

                % Check the selected language
                selectedLanguage = app.LanguageSwitch.Value;

                % Display the details in a message box based on the selected language
                if strcmp(selectedLanguage, 'ENG')
                    message = strrep(treatment.English, '\n\t', newline + "    ");
                elseif strcmp(selectedLanguage, 'RO')
                    message = strrep(treatment.Romanian, '\n\t', newline + "    ");
                else
                    message = 'Language not supported.';
                end

                % Display the details in a message box
                uialert(app.DiseaseDetectionUIFigure, message, 'Treatment Options', 'Icon', 'info');
            else
                % If no disease is detected, show a message
                uialert(app.DiseaseDetectionUIFigure, 'No treatment available.', 'No Treatment', 'Icon', 'info');
            end
        end


        function treatment = getTreatmentOptions(app, disease)
            keys_Treatment = {'Pepper__bell___Bacterial_spot', ...
                    'Pepper__bell___healthy', ...
                    'Potato___Early_blight', ...
                    'Potato___healthy', ...
                    'Potato___Late_blight', ...
                    'Tomato_Early_blight', ...
                    'Tomato_Late_blight', ...
                    'Tomato_Leaf_Mold', ...
                    'Tomato_Septoria_leaf_spot', ...
                    'Tomato_Spider_mites_Two_spotted_spider_mite', ...
                    'Tomato__Target_Spot', ...
                    'Tomato__Tomato_mosaic_virus', ...
                    'Tomato__Tomato_YellowLeaf__Curl_Virus', ...
                    'Tomato_Bacterial_spot', ...
                    'Tomato_healthy'};

           values_En_Treatment = {struct('English', [...
                    'Bacterial spot (Pepper):'...
                    '\n\tApply copper-based fungicides.'...
                    '\n\tRemove infected plant material.'...
                    '\n\tPractice crop rotation.'...
                    '\n\tEnsure proper spacing between plants.'...
                    '\n\tAvoid overhead irrigation.']),...
                struct('English', [...
                    'Healthy pepper plant:'...
                    '\n\tMaintain good soil moisture.'...
                    '\n\tUse disease-free seeds and plants.'...
                    '\n\tApply balanced fertilizers.'...
                    '\n\tMonitor for pests and diseases regularly.']),...
                struct('English', [...
                    'Early blight (Potato):'...
                    '\n\tRemove infected leaves and stems.'...
                    '\n\tApply fungicides containing chlorothalonil.'...
                    '\n\tAvoid overhead watering.'...
                    '\n\tPractice crop rotation.'...
                    '\n\tApply mulch to prevent soil splashing.']),...
                struct('English', [...
                    'Healthy potato plant:'...
                    '\n\tPlant disease-resistant potato varieties.'...
                    '\n\tEnsure proper spacing between plants.'...
                    '\n\tUse clean seed potatoes.'...
                    '\n\tPractice crop rotation.'...
                    '\n\tInspect plants regularly for signs of disease.']),...
                struct('English', [...
                    'Late blight (Potato):'...
                    '\n\tApply fungicides containing chlorothalonil or mancozeb.'...
                    '\n\tRemove and destroy infected plants.'...
                    '\n\tAvoid overhead watering.'...
                    '\n\tPractice crop rotation.'...
                    '\n\tHarvest potatoes promptly.']),...
                struct('English', [...
                    'Early blight (Tomato):'...
                    '\n\tApply copper-based fungicides.'...
                    '\n\tRemove and destroy infected leaves.'...
                    '\n\tMulch to prevent soil splashing.'...
                    '\n\tStake or cage plants for better air circulation.'...
                    '\n\tWater at the base of plants.']),...
                struct('English', [...
                    'Late blight (Tomato):'...
                    '\n\tApply fungicides containing chlorothalonil or copper.'...
                    '\n\tRemove infected leaves and stems.'...
                    '\n\tAvoid overhead watering.'...
                    '\n\tImprove air circulation around plants.'...
                    '\n\tDestroy infected plant debris.']),...
                struct('English', [...
                    'Leaf mold (Tomato):'...
                    '\n\tIncrease air circulation around plants.'...
                    '\n\tWater at the base of plants.'...
                    '\n\tUse drip irrigation to keep foliage dry.'...
                    '\n\tApply fungicides containing chlorothalonil.'...
                    '\n\tRemove infected leaves.']),...
                struct('English', [...
                    'Septoria leaf spot (Tomato):'...
                    '\n\tApply copper-based fungicides.'...
                    '\n\tRemove and destroy infected leaves.'...
                    '\n\tAvoid overhead watering.'...
                    '\n\tPrune lower leaves for better air circulation.'...
                    '\n\tWater at the base of plants.']),...
                struct('English', [...
                    'Spider mites (Tomato):'...
                    '\n\tSpray with insecticidal soap or neem oil.'...
                    '\n\tIncrease humidity to discourage mites.'...
                    '\n\tRemove heavily infested leaves.'...
                    '\n\tUse a strong jet of water to dislodge mites.'...
                    '\n\tIntroduce natural predators like ladybugs.']),...
                struct('English', [...
                    'Target spot (Tomato):'...
                    '\n\tApply copper-based fungicides.'...
                    '\n\tRemove and destroy infected leaves.'...
                    '\n\tAvoid overhead watering.'...
                    '\n\tStake or cage plants for better air circulation.'...
                    '\n\tWater at the base of plants.']),...
                struct('English', [...
                    'Tomato mosaic virus:'...
                    '\n\tRemove and destroy infected plants.'...
                    '\n\tUse disease-free seeds and plants.'...
                    '\n\tControl aphid populations to prevent spread.'...
                    '\n\tAvoid smoking near tomato plants.'...
                    '\n\tDisinfect tools to prevent transmission.']),...
                struct('English', [...
                    'Tomato yellow leaf curl virus:'...
                    '\n\tPlant virus-resistant tomato varieties.'...
                    '\n\tUse reflective mulch to deter whiteflies.'...
                    '\n\tApply insecticides to control whiteflies.'...
                    '\n\tRemove and destroy infected plants.'...
                    '\n\tControl weeds to reduce whitefly habitat.']),...
                struct('English', [...
                    'Tomato Bacterial spot:'...
                    '\n\tApply copper-based bactericides.'...
                    '\n\tRemove and destroy infected leaves.'...
                    '\n\tAvoid overhead watering.'...
                    '\n\tImprove air circulation around plants.'...
                    '\n\tUse disease-free seeds and plants.']),...
                struct('English', [...
                    'Healthy Tomato Plant:'...
                    '\n\tMaintain good soil moisture.'...
                    '\n\tUse balanced fertilizers.'...
                    '\n\tMonitor for pests and diseases regularly.'...
                    '\n\tPrune plants for better air circulation.'...
                    '\n\tUse mulch to retain moisture and suppress weeds.'])};


          values_Ro_Treatment = {struct('Romanian',['Pătarea bacteriană a ardeiului (Pepper):'...
                                '\n\tMici pete maro închis: Căutați aceste pete pe frunze și fructe. Acestea pot fi înconjurate de un halo galben.'...
                                '\n\tLeziuni înfundate în apă: Aceste zone adâncite pot apărea pe frunze și tulpini.'...
                                '\n\tOfilire și defoliere: În cazuri severe, frunzele pot ofili și cădea, afectând producția de fructe.']),...
            struct('Romanian',['Ardei gras sănătos:'...
                                '\n\tFrunze curate: Nu ar trebui să fie vizibile pete sau leziuni pe frunze.'...
                                '\n\tTulpini drepte: Tulpinile ar trebui să fie puternice și să nu ofilească.'...
                                '\n\tDezvoltare bună a fructelor: Căutați ardei sănătoși, în dezvoltare, fără pete.']),...
            struct('Romanian',['Alternarioza la cartof:'...
                                '\n\tInele concentrice pe frunze: Căutați inele maro întunecate care devin progresiv mai ușoare spre centru.'...
                                '\n\tGăuri de împușcare: Centrele inelelor maro pot deveni găuri în frunze.'...
                                '\n\tCreștere împiedicată: Alternarioza precoce poate încetini creșterea plantelor de cartofi și reduce randamentele.']),...
            struct('Romanian',['Cartof sănătos:'...
                                '\n\tFrunze verzi și sănătoase: Nu ar trebui să fie prezente pete sau leziuni pe frunze.'...
                                '\n\tCreștere sănătoasă: Planta ar trebui să crească constant, fără semne de dezvoltare împiedicată.'...
                                '\n\tTulpini puternice: Tulpinile ar trebui să fie verticale și să nu ofilească.']), ...
            struct('Romanian',['Mana cartofului:'...
                                '\n\tLeziuni înfundate în apă: Căutați zone întunecate și ude pe frunze și tulpini.'...
                                '\n\tRăspândire rapidă: Ciuperca târzie se poate răspândi rapid într-un câmp de cartofi.'...
                                '\n\tCiupercă pe tuberculi: În cazuri severe, boala poate infecta cartofii în curs de dezvoltare sub pământ.']),...
            struct('Romanian',['Alternarioza tomatelor:'...
                                '\n\tInele concentrice pe frunze: Similar cu alternarioza precoce a cartofilor, căutați inele maro întunecate cu centre mai ușoare.'...
                                '\n\tCădere de frunze: Pe măsură ce boala progresează, frunzele cu boli pot cădea.'...
                                '\n\tProducție redusă de fructe: Alternarioza precoce poate afecta randamentul general al roșiilor.']),...
            struct('Romanian',['Mana tomatelor:'...
                                '\n\tLeziuni înfundate în apă: Căutați zone întunecate și umede pe frunze, tulpini și fructe.'...
                                '\n\tRăspândire rapidă: La fel ca la cartof, această boală se poate răspândi rapid într-un câmp de roșii.'...
                                '\n\tPutrezirea fructelor: Mana târzie poate cauza roșiile infectate să putrezească și să devină inutilizabile.']),...
            struct('Romanian',['Pătarea cafenie a frunzelor de tomate (Fulgerarea tomatelor):'...
                                '\n\tPetice galbene: Inițial, frunzele dezvoltă pete galbene.'...
                                '\n\tPete maro: Pe măsură ce boala progresează, petele galbene devin maro și pot acoperi zone mai mari.'...
                                '\n\tCalitatea redusă a fructelor: Mana frunzelor poate afecta sănătatea generală și calitatea roșiilor în curs de dezvoltare.']),...
            struct('Romanian',['Septorioza tomatelor (Patarea neagră a frunzelor de tomate):'...
                                '\n\tMici pete întunecate: Căutați aceste pete pe frunze, cu un halo galben în jurul lor.'...
                                '\n\tGăuri de împușcare: Centrele petelor întunecate pot deveni găuri, creând un efect de "gaură de împușcare".'...
                                '\n\tDefoliere: În cazuri severe, poate apărea o pierdere mare de frunze din cauza unei infecții extinse.']),...
            struct('Romanian',['Păianjenul roșu comun (Păianjenul roșu al tomatelor):'...
                                '\n\tPetice galbene: Căutați o aparență galbenă și punctată pe suprafața superioară a frunzelor.'...
                                '\n\tPânză: Păianjenii roșii creează pânze fine pe partea inferioară a frunzelor.'...
                                '\n\tCădere de frunze: Infestările masive cu păianjeni pot face ca frunzele să ofilească și să cadă.']),...
            struct('Romanian',['Pet-spot (Fulgerarea țintei a tomatelor):'...
                                '\n\tCercuri concentrice: Căutați cercuri întunecate, maro cu centre mai ușoare pe frunze și tulpini.'...
                                '\n\tModel tip țintă: Cercurile concentrice pot semăna cu o țintă.'...
                                '\n\tCădere de frunze: Frunzele grav infectate pot cădea prematur.']),...
            struct('Romanian',['Virusul mozaicului tomatelor:'...
                                '\n\tFrunze distorsionate: Frunzele devin deformate și dezvoltă un model de mozaic cu zone verzi și întunecate.'...
                                '\n\tCreștere împiedicată: Virusul poate încetini creșterea plantei de tomate.'...
                                '\n\tRandament redus al fructelor: Producția totală de roșii poate fi semnificativ redusă.']),...
            struct('Romanian',['Virusul încurlării frunzelor de tomată (Virusul încurlării galbene a frunzelor de tomată):'...
                                '\n\tGalbenire și încurlare: Frunzele devin galbene și se încurcă în sus la margini.'...
                                '\n\tFrunze casante: Frunzele afectate devin casante și se pot sfărâma ușor.'...
                                '\n\tCreștere împiedicată: Asemănător cu virusul mozaicului tomatelor, acest virus poate împiedica creșterea plantei.']),...
            struct('Romanian',['Pătarea bacteriană a tomatelor:'...
                                '\n\tMici pete maro închis: Căutați aceste pete pe frunze, tulpini și fructe.'...
                                '\n\tLeziuni înfundate în apă: Aceste zone adâncite pot apărea pe frunze și tulpini.'...
                                '\n\tOfilire și defoliere: În cazuri severe, frunzele pot ofili și cădea, afectând producția de fructe.']),...
            struct('Romanian',['Tomate sănătoase:'...
                                '\n\tFrunze verzi și sănătoase: Nu ar trebui să fie prezente pete sau leziuni pe frunze.'...
                                '\n\tTulpini verticale: Tulpinile ar trebui să fie puternice și să nu ofilească.'...
                                '\n\tDezvoltare bună a fructelor: Căutați roșii sănătoase, în dezvoltare, fără pete.'])};
    
            
            treatmentOptions_En = containers.Map(keys_Treatment, values_En_Treatment);
            treatmentOptions_Ro = containers.Map(keys_Treatment, values_Ro_Treatment);
            
            treatment = struct('English', 'Treatment not available.', 'Romanian', 'Tratament indisponibil.');
            selectedLanguage = app.LanguageSwitch.Value;
            % Display the details in a message box based on the selected language
            if strcmp(selectedLanguage, 'ENG')
                treatmentOptions = treatmentOptions_En;
            elseif strcmp(selectedLanguage, 'RO')
                treatmentOptions = treatmentOptions_Ro;
            else
                return;
            end

            % Check if the disease name exists in the map
            if isKey(treatmentOptions, disease)
                treatment = treatmentOptions(disease);
            else
                treatment = 'No treatment options available.';
            end
        end
    end
            %options = strrep(options, '\n', newline);
            %options = strrep(options, '\t', sprintf('\t'));
        
        %end
    %end

    % App creation and deletion
    methods (Access = public)

        % Construct app
        function app = App
            % Create UIFigure and components
            createComponents(app)
            % Register the app with App Designer
            registerApp(app, app.DiseaseDetectionUIFigure)
            
            % Mapam bolile
            englishNames = {'Pepper__bell___Bacterial_spot','Pepper__bell___healthy','Potato___Early_blight','Potato___healthy','Potato___Late_blight','Tomato_Early_blight','Tomato_Late_blight','Tomato_Leaf_Mold','Tomato_Septoria_leaf_spot','Tomato_Spider_mites_Two_spotted_spider_mite','Tomato__Target_Spot','Tomato__Tomato_mosaic_virus','Tomato__Tomato_YellowLeaf__Curl_Virus','Tomato_Bacterial_spot','Tomato_healthy'};
            romanianNames = {'Patarea frunzelor si basicarea fructelor de ardei','Ardei gras sanatos','Alternarioza la cartof','Cartof sanatos','Ciuperca Cartofului','Alternarioza tomatelor','Mana tomatelor','Patarea cafenie a frunzelor de tomate','Septorioza tomatelor','Paianjenul rosu comun','Pătarea brună a frunzelor de tomate','Mozaicul tomatelor','Virusul ingalbenirii si rasucirii frunzelor de tomate','Pătarea frunzelor și bășicarea fructelor tomatelor','Tomate sanatoase'};
            app.DiseaseNameMapping = containers.Map(englishNames, romanianNames);
        end

        % Code that executes before app deletion
        function delete(app)
            % Delete UIFigure when app is deleted
            delete(app.DiseaseDetectionUIFigure)
        end
    end
end